id: P005377
initial_creation_type: ocr
source_metadata:
  id: bdr:W22677
  title: སྐྱེས་རབས་སོ་བཞི་པ།
  author: ''
  volumes:
    04b3399b7b23435d82bb4a47605aebeb:
      image_group_id: I1KG1714
      title: ''
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
